# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# ===================================================================

spring:
  name: mini-board-svc
  profiles:
    active: local
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/
    prefix: classpath:/templates/

server:
  port: 8080
#  servlet:
#    context-path: /mini-board/api
  error:
    whitelabel:
      enabled: false

logging:
  file:
  path: /svc/logs/${spring.name}
