# ===================================================================
# LOCAL SPRING BOOT PROPERTIES
# ===================================================================

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://172.30.1.11:3306/MINI_BOARD?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/mini_board?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      username: root
      password: root
      maximum-pool-size: 3
  jpa:
    database: mysql
  profiles:
    include: oauth

server:
  port: 8080

logging:
  config: classpath:logback/logback-local.xml

