# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# ===================================================================

spring:
  name: mini-board-svc
  profiles:
    active: local

#server:
  # port: 8080
    #servlet:
    #context-path: /mini-board/api
    #error:
      #whitelabel:
    #enabled: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

logging:
  file:
    path: /svc/logs/${spring.name}
